server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3309/Shopee_DB"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
  security:
    user:
      name: admin
      password: admin@123
  app:
    jwtSecret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    jwtExpiration: 30000000
    jwtCookieName: shoppe_clone_app
  web:
    resources:
      static-locations:
        - file:///D:/JAVAWEB/BE/shopee-clone-backend/images/

project:
  image: "images/"